GET http://localhost:5000/posts HTTP/1.1 authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF0dHkiLCJpYXQiOjE2NDY4NTYzNzgsImV4cCI6MTY0Njg1NjM5M30.qt5tVK9aE6NDYjpeiax8x95UIEo5_PQPGFQiJsGzySk ### POST http://localhost:4000/login HTTP/1.1 content-type: application/json
{
"username": "Patty"
}

POST http://localhost:4000/token HTTP/1.1 Content-Type: application/json
{
"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF0dHkiLCJpYXQiOjE2NDY5MzU2MDJ9.xbkEqDcLMj3jEtv4DN8J7L9bgT8GpXOynYgcHpYQCo8"
}

DELETE http://localhost:4000/logout HTTP/1.1. Content-Type: application/json
{
"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF0dHkiLCJpYXQiOjE2NDY5MzU2MDJ9.xbkEqDcLMj3jEtv4DN8J7L9bgT8GpXOynYgcHpYQCo8"
}